"""Step 4: check the model, then compute what every DAX measure SHOULD show in Power BI.

    ./venv/bin/python check.py

1. Integrity asserts: unique dimension keys, no orphan foreign keys, and the BTS rules the measures rely on.
2. Writes expected_values.md, the numbers the finished Power BI report must match, card for card.
kpis() is the pandas twin of measures.dax, and preview.py reuses it, so the web preview shows the same numbers.
"""
from pathlib import Path

import pandas as pd

HERE = Path(__file__).parent
M = HERE / "model"
CAUSES = {"CarrierDelay": "Carrier", "WeatherDelay": "Weather", "NASDelay": "National Air System",
          "SecurityDelay": "Security", "LateAircraftDelay": "Late-arriving aircraft"}


def load():
    fact = pd.read_csv(M / "FactFlights.csv", dtype={"CancelCode": "string"})
    dims = {n: pd.read_csv(M / f"{n}.csv") for n in ["DimDate", "DimCarrier", "DimAirport", "DimCancelReason"]}
    return fact, dims


def kpis(f):
    """Same definitions as measures.dax / model.md."""
    scheduled = len(f)
    cancelled = int(f["Cancelled"].sum())
    diverted = int(f["Diverted"].sum())
    completed = scheduled - cancelled - diverted
    late = int((f["ArrDel15"] == 1).sum())
    cause_min = {c: int(f[c].sum()) for c in CAUSES}
    total_min = sum(cause_min.values())
    return {
        "scheduled": scheduled, "cancelled": cancelled, "diverted": diverted, "completed": completed,
        "late": late,
        "on_time_pct": (completed - late) / completed if completed else None,
        "cancel_rate": cancelled / scheduled if scheduled else None,
        "avg_arr_delay": f["ArrDelay"].mean(),                       # blanks skipped, like AVERAGE()
        "avg_delay_when_late": f.loc[f["ArrDel15"] == 1, "ArrDelay"].mean(),
        "cause_min": cause_min, "total_delay_min": total_min,
        "weather_share": cause_min["WeatherDelay"] / total_min if total_min else None,
        "weather_cancellations": int((f["CancelCode"] == "B").sum()),
    }


def integrity(fact, dims):
    for name, key in [("DimDate", "DateKey"), ("DimCarrier", "CarrierCode"), ("DimAirport", "AirportCode"),
                      ("DimCancelReason", "CancelCode")]:
        assert dims[name][key].is_unique, f"{name}.{key} not unique"
    for col, name, key in [("DateKey", "DimDate", "DateKey"), ("CarrierCode", "DimCarrier", "CarrierCode"),
                           ("OriginCode", "DimAirport", "AirportCode"), ("DestCode", "DimAirport", "AirportCode"),
                           ("CancelCode", "DimCancelReason", "CancelCode")]:
        orphans = set(fact[col].dropna()) - set(dims[name][key])
        assert not orphans, f"FactFlights.{col} values missing from {name}: {sorted(orphans)[:5]}"

    completed = (fact["Cancelled"] == 0) & (fact["Diverted"] == 0)
    # the measures assume: arrival delay exists exactly for completed flights
    assert (fact["ArrDel15"].notna() == completed).all(), "ArrDel15 should be filled exactly for completed flights"
    assert (fact["ArrDelay"].notna() == completed).all(), "ArrDelay should be filled exactly for completed flights"
    assert (fact["CancelCode"].notna() == (fact["Cancelled"] == 1)).all(), "cancel code iff cancelled"
    assert ((fact["ArrDel15"] == 1) == (fact["ArrDelay"] >= 15)).fillna(True).all(), "ArrDel15 must mean ArrDelay >= 15"
    # BTS splits a late arrival's delay into the 5 cause columns; they should add up to the arrival delay
    late = fact[fact["ArrDel15"] == 1]
    match = (late[list(CAUSES)].sum(axis=1) == late["ArrDelay"]).mean()
    assert match > 0.99, f"cause minutes match ArrDelay for only {match:.1%} of late flights"
    assert fact.loc[fact["ArrDel15"] != 1, list(CAUSES)].isna().all().all(), "causes only on late flights"
    return match


def pct(x):
    return f"{x:.1%}"


def table(rows, cols):
    head = "| " + " | ".join(cols) + " |\n|" + "---|" * len(cols) + "\n"
    return head + "".join("| " + " | ".join(str(r[c]) for c in cols) + " |\n" for r in rows)


def expected_md(fact, dims):
    k = kpis(fact)
    out = ["# Expected values\n",
           "What each measure in `measures.dax` must show in Power BI (no filters unless stated). "
           "Generated by `check.py` from the files in `model/`.\n",
           "## Cards (all Florida departures, Aug 2025 - Jul 2026)\n",
           table([
               {"Measure": "Scheduled Flights", "Value": f"{k['scheduled']:,}"},
               {"Measure": "Cancelled Flights", "Value": f"{k['cancelled']:,}"},
               {"Measure": "Diverted Flights", "Value": f"{k['diverted']:,}"},
               {"Measure": "Completed Flights", "Value": f"{k['completed']:,}"},
               {"Measure": "Late Arrivals", "Value": f"{k['late']:,}"},
               {"Measure": "On-Time %", "Value": pct(k["on_time_pct"])},
               {"Measure": "Cancellation Rate", "Value": pct(k["cancel_rate"])},
               {"Measure": "Avg Arrival Delay (min)", "Value": f"{k['avg_arr_delay']:.2f}"},
               {"Measure": "Avg Delay When Late (min)", "Value": f"{k['avg_delay_when_late']:.2f}"},
               {"Measure": "Total Delay Min", "Value": f"{k['total_delay_min']:,}"},
               {"Measure": "Weather Share of Delay Min", "Value": pct(k["weather_share"])},
               {"Measure": "Weather Cancellations", "Value": f"{k['weather_cancellations']:,}"},
           ], ["Measure", "Value"]),
           "\n## Delay minutes by cause\n",
           table([{"Cause": CAUSES[c], "Minutes": f"{v:,}", "Share": pct(v / k["total_delay_min"])}
                  for c, v in sorted(k["cause_min"].items(), key=lambda x: -x[1])], ["Cause", "Minutes", "Share"])]

    fl = k["on_time_pct"]
    ap = dims["DimAirport"].set_index("AirportCode")
    rows = []
    for code, g in fact.groupby("OriginCode"):
        a = kpis(g)
        rows.append({"Airport": code, "City": ap.loc[code, "City"], "Flights": a["scheduled"],
                     "On-Time %": pct(a["on_time_pct"]), "Cancellation Rate": pct(a["cancel_rate"]),
                     "On-Time vs Florida (pts)": f"{(a['on_time_pct'] - fl) * 100:+.1f}"})
    rows.sort(key=lambda r: -r["Flights"])
    for r in rows:
        r["Flights"] = f"{r['Flights']:,}"
    out += ["\n## By origin airport (slicer on DimAirport)\n",
            table(rows, ["Airport", "City", "Flights", "On-Time %", "Cancellation Rate", "On-Time vs Florida (pts)"])]

    names = dims["DimCarrier"].set_index("CarrierCode")["CarrierName"]
    rows = [{"Carrier": names[c], "Flights": len(g), "otp": kpis(g)["on_time_pct"]} for c, g in fact.groupby("CarrierCode")]
    rows.sort(key=lambda r: -r["otp"])
    for i, r in enumerate(rows, 1):
        r.update({"Carrier On-Time Rank": i, "On-Time %": pct(r["otp"]), "Flights": f"{r['Flights']:,}"})
    out += ["\n## By carrier\n", table(rows, ["Carrier On-Time Rank", "Carrier", "Flights", "On-Time %"])]

    months = dims["DimDate"].drop_duplicates("MonthKey").set_index("MonthKey")["MonthLabel"]
    rows = []
    for mk, g in fact.groupby(fact["DateKey"] // 100):
        a = kpis(g)
        rows.append({"Month": months[mk], "Flights": f"{a['scheduled']:,}", "On-Time %": pct(a["on_time_pct"]),
                     "Cancellation Rate": pct(a["cancel_rate"]), "Weather Cancellations": a["weather_cancellations"]})
    out += ["\n## By month\n", table(rows, ["Month", "Flights", "On-Time %", "Cancellation Rate", "Weather Cancellations"])]
    return "".join(out)


if __name__ == "__main__":
    fact, dims = load()
    match = integrity(fact, dims)
    (HERE / "expected_values.md").write_text(expected_md(fact, dims))
    k = kpis(fact)
    print(f"integrity OK ({len(fact):,} flights; cause minutes add up for {match:.2%} of late arrivals)")
    print(f"On-Time % {k['on_time_pct']:.1%} | Cancellation Rate {k['cancel_rate']:.2%} | "
          f"Avg Arrival Delay {k['avg_arr_delay']:.1f} min -> expected_values.md")
